FROM docker.elastic.co/logstash/logstash:8.10.4

# Remove default config
RUN rm -f /usr/share/logstash/pipeline/logstash.conf

# Copy our custom configuration
COPY logstash.conf /usr/share/logstash/pipeline/logstash.conf
